
manta_samples: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/sample_lists/manta.samples.txt

gridss_samples: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/sample_lists/gridss.samples.txt

delly_samples: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/sample_lists/delly.samples.txt

smoove_samples: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/sample_lists/smoove.samples.txt

cram_samples: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/sample_lists/crams.txt

chr_list: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/reference/UU_Cfam_GSD_1.0_ROSY/chrms.txt

reference_fasta: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/reference/UU_Cfam_GSD_1.0_ROSY/UU_Cfam_GSD_1.0_ROSY.fa

cache: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/reference/UU_Cfam_GSD_1.0_ROSY/cache

gtf: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/reference/UU_Cfam_GSD_1.0_ROSY/UU_Cfam_GSD_1.0_ROSY.refSeq.ensformat.gtf.gz

sif: /gpfs_common/share01/stern/mwvandew/make_SV_vcf/sif/catmike_wags.sif

suffix: UU_Cfam_GSD_1.0_ROSY.left_aligned

ref: UU_Cfam_GSD_1.0_ROSY 

species: dog

conda_envs:
  delly: delly
  gridss: gridss
  smoove: smoove
  manta: manta



