
manta_samples: /gpfs_common/share01/stern/mwvandew/sv_dogs/manta.samples.txt

gridss_samples: /gpfs_common/share01/stern/mwvandew/sv_dogs/gridss.samples.txt

delly_samples: /gpfs_common/share01/stern/mwvandew/sv_dogs/delly.samples.txt

chr_list: /gpfs_common/share01/stern/mwvandew/sv_dogs/reference/UU_Cfam_GSD_1.0_ROSY/chrms.txt

reference_fasta: /gpfs_common/share01/stern/mwvandew/sv_dogs/reference/UU_Cfam_GSD_1.0_ROSY/UU_Cfam_GSD_1.0_ROSY.fa

gtf: /gpfs_common/share01/stern/mwvandew/sv_dogs/reference/UU_Cfam_GSD_1.0_ROSY/UU_Cfam_GSD_1.0_ROSY.refSeq.ensformat.gtf.gz

sif: /gpfs_common/share01/stern/mwvandew/sv_dogs/sif/catmike_wags.sif

suffix: _pe_sorted_dedup

ref: UU_Cfam_GSD_1.0_ROSY 

species: dog

conda_envs:
  delly: delly
  gridss: gridss
  smoove: smoove
  manta: manta



